server:
  port: 8601
spring:
  application:
    name: smart-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: route_member
          uri: 'lb://smart-member'
          predicates:
            - Path=/api/v1/member/**
          filters:
            - 'RewritePath=/api/v1/(?<segment>.*),/$\{segment}'
        - id: route_post
          uri: 'lb://smart-post'
          predicates:
            - Path=/api/v1/post/**
          filters:
            - 'RewritePath=/api/v1/(?<segment>.*),/$\{segment}'
        - id: route_notify
          uri: 'lb://smart-notify'
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - 'RewritePath=/api/v1/(?<segment>.*),/$\{segment}'
        - id: route_thirdpart
          uri: 'lb://smart-thirdpart'
          predicates:
            - Path=/api/v1/thirdpart/**
          filters:
            - 'RewritePath=/api/v1/(?<segment>.*),/$\{segment}'
        - id: route_search
          uri: 'lb://smart-search'
          predicates:
            - Path=/api/v1/search/**
          filters:
            - 'RewritePath=/api/v1/(?<segment>.*),/$\{segment}'
        - id: route_product
          uri: 'lb://smart-product'
          predicates:
            - Path=/api/v1/product/**
          filters:
            - 'RewritePath=/api/v1/(?<segment>.*),/$\{segment}'
        - id: route_task
          uri: 'lb://smart-task'
          predicates:
            - Path=/api/v1/task/**
          filters:
            - 'RewritePath=/api/v1/(?<segment>.*),/$\{segment}'
        - id: route_gateway
          uri: 'lb://smart-gateway'
          predicates:
            - Path=/api/v1/gateway/**
          filters:
            - 'RewritePath=/api/v1/(?<segment>.*),/$\{segment}'
  redis:
    database: 0
    host: 172.19.0.2
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis-plus:
  mapper-locations: 'classpath:/mapper/**/*.xml'
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
sa-token:
  token-name: access_token
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: false
  is-share: true
  token-style: simple-uuid
  is-log: true
  isReadBody: true
  isReadHead: true
  isReadCookie: true
  autoRenew: true
  isPrint: false
